version: "3.4"
services:
  #########################[ POSTGRESQL ]############################
  postgresql:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgreadmin
      - POSTGRES_PASSWORD=postgrepassword
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data
  #-----------------------------------------------------------------#
  ############################[ MONGODB ]##############################
  mongodb:
      image: mongo:5.0
      ports:
        - 27017:27017
      volumes:
        - mongodb:/data
      environment:
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=mongopassword
  #-----------------------------------------------------------------#
  ##########################[ RABBITMQ ]#############################
  rabbitmqmb:
    image: "rabbitmq:3-management"
    hostname: "rabbitmqmb"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmquser"
      RABBITMQ_DEFAULT_PASS: "rabbitmqpassword"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmqmb"
    volumes:
      - rabbitmqmb:/data
#-----------------------------------------------------------------#
volumes:
  postgresql:
    driver: local
  mongodb:
    driver: local
  rabbitmqmb:
    driver: local
